package rss

import (
	"drebollo/twitchtopodcast/internal/models"
	"fmt"
	"strconv"
	"time"

	"github.com/eduncan911/podcast"
)

func Generator(channel models.Channel) podcast.Podcast {

	title := channel.DisplayName
	link := fmt.Sprintf("https://www.twitch.tv/%s", channel.Login)
	description := channel.Description
	createAt := channel.CreatedAt
	lastBuildDate := time.Now()
	img := channel.ProfileImageURL

	podcast := podcast.New(title, link, description, &createAt, &lastBuildDate)
	podcast.AddAuthor(channel.DisplayName, link)
	podcast.AddImage(img)
	podcast.Generator = "twitch2podcast.com | go podcast v1.3.1 (github.com/eduncan911/podcast)"
	return podcast
}

func GenerateEpisode(vod models.Video) *podcast.Item {

	vodLink := fmt.Sprintf("https://www.twitch.tv/videos/%d", vod.ID)

	if vod.IsPublic {
		episode := podcast.Item{Title: vod.Title, Description: "default description", Link: vodLink}

		episode.AddPubDate(&vod.CreatedAt)
		episode.AddEnclosure(*vod.AudioURL, podcast.M4A, int64(vod.LengthSeconds))
		episode.IDuration = strconv.Itoa(vod.LengthSeconds)
		episode.Description = fmt.Sprintf("<h1>%s</h1><img src='%s'><a href='%s'>%s</a><br><p>Podcast generated by <a href='https://www.twitch2podcast.com'>twitch2podcast.com</a></p>", vod.Title, vod.PreviewThumbnailURL, vodLink, vodLink)
		return &episode
	}
	return nil
}
